import { Album, CheckCircle2, LayoutTemplate, MonitorPlay, QrCode, ShieldCheck } from "lucide-react"

import { LandingSection } from "@/components/landing/landing-section"
import { PageShell } from "@/components/ui/page-shell"

const features = [[LayoutTemplate, "Poster Studio", "Điểm bắt đầu để sự kiện có một diện mạo riêng.", "primary"], [MonitorPlay, "Public Wall", "Nơi lời chúc và media trở thành trải nghiệm chung.", "primary"], [QrCode, "QR sự kiện", "Một lối vào đơn giản cho khách mời.", "support"], [MessageCircleIcon, "Lời chúc và media", "Giữ lại những điều đáng nhớ.", "support"], [ShieldCheck, "Kiểm duyệt nội dung", "Chủ sự kiện có quyền kiểm soát trước khi công khai.", "support"], [Album, "Album sau sự kiện", "Câu chuyện tiếp tục sau buổi tiệc.", "support"]] as const
function MessageCircleIcon(props: { className?: string }) { return <svg aria-hidden="true" className={props.className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 11.5a8.38 8.38 0 0 1-9 8.5 8.5 8.5 0 0 1-4.2-1.1L3 20l1.1-4.8A8.5 8.5 0 1 1 21 11.5Z" /><path d="m8 12 2 2 4-4" /></svg> }

export function FeatureBento() {
  return <LandingSection id="features" className="bg-surface-sunken"><PageShell><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Feature Highlights</p><h2 className="mt-3 font-heading text-3xl font-bold tracking-tight sm:text-4xl">Sáu thành phần, một câu chuyện rõ ràng</h2><p className="mt-4 text-base leading-7 text-muted-foreground">Poster Studio và Public Wall dẫn nhịp; các tính năng còn lại hỗ trợ trước, trong và sau sự kiện.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-2">{features.map(([Icon, title, description, priority], index) => <article key={title} className={`rounded-3xl border bg-card p-6 ${priority === "primary" ? "min-h-56 bg-[linear-gradient(145deg,var(--brand-50),var(--card))] sm:p-8" : "sm:p-7"}`}><div className="flex items-start justify-between gap-4"><div className="flex size-12 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-6" /></div>{priority === "primary" ? <span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">Ưu tiên trải nghiệm</span> : <span className="text-xs text-muted-foreground">{String(index + 1).padStart(2, "0")}</span>}</div><h3 className="mt-6 font-heading text-xl font-semibold">{title}</h3><p className="mt-2 max-w-md text-sm leading-7 text-muted-foreground">{description}</p></article>)}</div></PageShell></LandingSection>
}
