import type { StickerCharacterDefinition } from "./types"

export const STICKER_MANIFEST: StickerCharacterDefinition[] = [
  {
    id: "anime-party",
    name: "Chibi Party Girl",
    src: "/stickers/anime-party.png",
    personality: "cheerful",
    initialPosition: { x: 0.88, y: 0.12 },
    mobilePosition: { x: 0.85, y: 0.1 },
    size: { desktop: 140, mobile: 100 },
    anchor: { x: 0.5, y: 0.5 },
    zIndex: 30,
    entranceAction: "peek",
    idleActions: ["bounce", "dance", "wave", "sparkle", "jump", "throw-confetti"],
    interactionActions: ["jump", "celebrate", "throw-confetti", "dance"],
    celebrationAction: "throw-confetti",
    clickable: true,
    draggable: true,
    followPointer: true,
    speechMessages: {
      greeting: ["Chào mừng bạn đến với sự kiện!", "Mở thiệp cùng mình nhé! ✨"],
      rsvp: ["Gửi lời chúc ngay thôi!", "Hẹn gặp bạn tại bữa tiệc! 🎉"],
      celebration: ["Tuyệt vời quá! 🥳", "Hẹn gặp bạn tại sự kiện nhé!"],
      idle: ["Tiệc sắp bắt đầu rồi! 🎈", "Hôm nay thật là đẹp trời!", "Nhún nhảy cùng mình nào! 🎶"],
      clicked: ["Yay! Bạn đã bấm vào mình! 💖", "Cùng ăn mừng nào! 🎊"],
    },
    safeZone: { padding: 16 },
  },
  {
    id: "neko-heart",
    name: "Neko Sparkle Cat",
    src: "/stickers/anime-heart.png",
    personality: "shy",
    initialPosition: { x: 0.12, y: 0.82 },
    mobilePosition: { x: 0.12, y: 0.85 },
    size: { desktop: 130, mobile: 92 },
    anchor: { x: 0.5, y: 0.5 },
    zIndex: 30,
    entranceAction: "float",
    idleActions: ["idle", "float", "sparkle", "blink", "wave", "bounce"],
    interactionActions: ["wave", "sparkle", "bounce"],
    celebrationAction: "sparkle",
    clickable: true,
    draggable: true,
    followPointer: false,
    speechMessages: {
      greeting: ["Xin chào... 🌸", "Mong bạn có trải nghiệm tuyệt vời!"],
      rsvp: ["Để lại lời chúc thương yêu nhé! 💖", "Meow~ Cảm ơn bạn!"],
      celebration: ["Thật ấm áp! 💕", "Yêu bạn nhiều!"],
      idle: ["Meow~ ✨", "Trái tim đang phát sáng nè! 💖", "Chúc bạn một ngày ngọt ngào! 🌸"],
      clicked: ["Purr~ Cảm ơn bạn đã quan tâm! 🐾", "Mèo yêu bạn! 💖"],
    },
    safeZone: { padding: 14 },
  },
  {
    id: "prince-crown",
    name: "Chibi Prince Crown",
    src: "/stickers/anime-crown.png",
    personality: "energetic",
    initialPosition: { x: 0.12, y: 0.15 },
    mobilePosition: { x: 0.12, y: 0.12 },
    size: { desktop: 135, mobile: 96 },
    anchor: { x: 0.5, y: 0.5 },
    zIndex: 30,
    entranceAction: "jump",
    idleActions: ["look-at-pointer", "bounce", "sparkle", "jump", "dance", "point-to-cta"],
    interactionActions: ["point-to-cta", "celebrate", "jump"],
    celebrationAction: "celebrate",
    clickable: true,
    draggable: true,
    followPointer: true,
    speechMessages: {
      greeting: ["Thân mời VIP Guest! 👑", "Chúc bạn một ngày rực rỡ!"],
      rsvp: ["Bấm nút gửi lời chúc nào! 🌟", "Đừng quên xác nhận tham dự!"],
      celebration: ["Rực rỡ đẳng cấp Royal! 👑", "Thắng lớn rồi!"],
      idle: ["Phép thuật ngôi sao! ✦", "Vương miện lấp lánh nè! ✨", "Chào mừng thượng khách! 👑"],
      clicked: ["Bùa may mắn gửi đến bạn! 👑✨", "Tiến lên thôi nào!"],
    },
    safeZone: { padding: 16 },
  },
]
